# Generated by Django 4.2.1 on 2023-06-03 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('link_precedence', models.CharField(choices=[('PRI', 'primary'), ('SEC', 'secondary')], default='PRI', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('linked_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='identity.contact')),
            ],
        ),
    ]
