# Generated by Django 4.2.1 on 2023-06-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='link_precedence',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], default='primary', max_length=10),
        ),
    ]
